### ISSUE TITLE
Idées

### ISSUE THREAD

**Issue by Nqts1337** [HideakiAtsuyo/BetterGrabber#1]
~~- Obtenir plus d'informations par exemple : Pseudo, id, si il a nitro, email, number, quand il a été créé etc..~~(Finished)
~~- clé windows (je pense pas que ça soit possible mais vas y on dit quand même)~~(Impossible)
~~- ip info par exemple : IP (logique), ISP, pays, région, ville, zip code (j'ai plus le nom en français)~~

on verra les prochaines idées

**Comment by Sief1334** [comment]
> * Obtenir plus d'informations par exemple : Pseudo, id, si il a nitro, email, number, quand il a été créé etc..
> * ip info par exemple : IP (logique), ISP, pays, région, ville, zip code (j'ai plus le nom en français)
>   ~- clé windows (je pense pas que ça soit possible mais vas y on dit quand même)~
> 
> on verra les prochaines idées

you managed to make it work

**Comment by HideakiAtsuyo** [comment]
Applied all updates
