### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by SwiftDevXX** [HideakiAtsuyo/BetterGrabber#12]
Yo so i put in the webhook and it still doesnt do anything

**Comment by HideakiAtsuyo** [comment]
> Yo so i put in the webhook and it still doesnt do anything

Screenshot the config.

**Comment by SwiftDevXX** [comment]
![image](https://user-images.githubusercontent.com/96430815/149718279-bce44802-d723-49cd-9870-78c63beea226.png)
![image](https://user-images.githubusercontent.com/96430815/149718319-4af84815-ce66-414b-a079-b56e8ebf420a.png)
![image](https://user-images.githubusercontent.com/96430815/149718337-e13b1387-f2ad-4c8b-96f3-a0b21b9026e8.png)

**Comment by HideakiAtsuyo** [comment]
I the config. Not the whole code.

Read the default example config I will not help you to understand what you missed.

**Comment by SwiftDevXX** [comment]
i do not get this part

Fill up the config

**Comment by HideakiAtsuyo** [comment]
> i do not get this part
> 
> Fill up the config

I will let you figure it out everything is in the ReadMe.

**Comment by SwiftDevXX** [comment]
but im a retard

**Comment by HideakiAtsuyo** [comment]
> but im a retard

Good luck it's not hard to read the default config to understand how you have to fill it.

**Comment by SwiftDevXX** [comment]
well that means i wont be fixing it coz im dummy

**Comment by HideakiAtsuyo** [comment]
> well that means i wont be fixing it coz im dummy

No problem.
