### ISSUE TITLE
User Premium Status

### ISSUE THREAD

**Issue by QUEPROO** [HideakiAtsuyo/BetterGrabber#13]
User Premium Status : undefined or "7" (in the console)

![LolIGot7777777](https://user-images.githubusercontent.com/98923013/152708617-eda341f2-526b-4a32-ada8-f3c0538d4d11.png)

**Comment by HideakiAtsuyo** [comment]
Should be fixed right now.

**Comment by HideakiAtsuyo** [comment]
https://github.com/HideakiAtsuyo/BetterGrabber/commit/8119962ca89c1ed868ac937bf499a1cd9d00b570

Fixed.
