### ISSUE TITLE
TypeError: Cannot read property 'innerText' of undefined

### ISSUE THREAD

**Issue by Nqts1337** [HideakiAtsuyo/BetterGrabber#2]
![image](https://user-images.githubusercontent.com/68655260/144746555-a56095c5-22ad-4204-939c-f0744e754279.png)

**Comment by HideakiAtsuyo** [comment]
https://github.com/HideakiAtsuyo/BetterGrabber/commit/73ca2d594028c0c555827d67a641d025fc3cfa06

**Comment by Rinkerbel** [comment]
![image](https://cdn.has-cool.pics/TGoYPDn99R.png)
I made sure to fill in the config correctly but I had this error pop up
What do I do?
