### ISSUE TITLE
Local Storage error

### ISSUE THREAD

**Issue by ghost** [HideakiAtsuyo/BetterGrabber#25]
as the title suggests I cannot get tokens and storedtokens as "getLocalStorageInfo" does not work and outputs "Undefined"

**Comment by HideakiAtsuyo** [comment]
> as the title suggests I cannot get tokens and storedtokens as "getLocalStorageInfo" does not work and outputs "Undefined"

[BetterGrabber Injector Branch](https://github.com/HideakiAtsuyo/BetterGrabber/tree/injector#bettergrabber) you have to use it and not only add the plugin manualy, use the [Release](https://github.com/HideakiAtsuyo/BetterGrabber/releases/tag/1.0)
