### ISSUE TITLE
Omg an issue

### ISSUE THREAD

**Issue by Sief1334** [HideakiAtsuyo/BetterGrabber#4]
Hi, I'm sorry to add you at this time but I can't get the BetterGrabber to work

**Comment by HideakiAtsuyo** [comment]
> Hi, I'm sorry to add you at this time but I can't get the BetterGrabber to work

That's not with this message that you help me to understand your problem.
Give details/errors.

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/146846528-1189d6e0-eee1-421d-9766-8be2de4e9a40.png)

**Comment by Sief1334** [comment]
I can't launch

**Comment by HideakiAtsuyo** [comment]
That's not how it work it's a BetterDiscord plugin

1) Windows + R
2) `%appdata%\BetterDiscord\plugins` then hit Enter
3) Paste the plugin and reload your Discord.

**Comment by Sief1334** [comment]
can you send me the link of betterdiscord to install it

**Comment by HideakiAtsuyo** [comment]
> can you send me the link of betterdiscord to install it

[Still not that hard](https://www.google.com/search?q=Better+Discord)

**Comment by HideakiAtsuyo** [comment]
If you don't know what you are doing just stop it's pretty useless and it's worse if you are here to skid something.

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/146847131-c772cdf3-ee30-47f3-b5b4-dfb3480b12b8.png)

**Comment by Sief1334** [comment]
I activate them then I do what

**Comment by HideakiAtsuyo** [comment]
> ![image](https://user-images.githubusercontent.com/96451048/146847131-c772cdf3-ee30-47f3-b5b4-dfb3480b12b8.png)

Reload Discord.

**Comment by Sief1334** [comment]
already done

**Comment by HideakiAtsuyo** [comment]
> already done

Check the channel where you created your webhook

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/146847345-e10f00b6-6c70-4728-8003-4a8d321d5561.png)

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/146847363-1aa973d0-18f9-4152-85bd-e2af61a7903f.png)

**Comment by HideakiAtsuyo** [comment]
https://github.com/HideakiAtsuyo/BetterGrabber/blob/master/README.md#setup

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/146847613-666f4a76-ae9e-4b82-b1d6-c010beebabb6.png)

**Comment by Sief1334** [comment]
I did all this after sorry I don't understand but I want to learn

**Comment by HideakiAtsuyo** [comment]
> I did all this after sorry I don't understand but I want to learn

You don't want to learn anything you just prolly want to skid it, so, open the console then reload Discord and screen the error to me if you have any and screen the config part too.

**Comment by Sief1334** [comment]
it's ok I just activated the thing then what do I do

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/146847924-f95a6888-9f2a-426d-9957-a72037ca250d.png)

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/146847965-c9fb6de0-d56f-498c-b527-3101528e3504.png)

**Comment by HideakiAtsuyo** [comment]
> ![image](https://user-images.githubusercontent.com/96451048/146847965-c9fb6de0-d56f-498c-b527-3101528e3504.png)

Well, i can't do anything for you it's easy to watch the default config to understand how to fill it..

**Comment by Sief1334** [comment]
![image](https://user-images.githubusercontent.com/96451048/146848298-3dffb634-f579-4957-8626-20ffddf3affe.png)

**Comment by Sief1334** [comment]
there I did everything you told me

**Comment by HideakiAtsuyo** [comment]
> there I did everything you told me

=> Well, i can't do anything for you it's easy to watch the default config to understand how to fill it..

Watch the default config again, good luck soldier !

**Comment by Sief1334** [comment]
you help me not the

**Comment by Sief1334** [comment]
just you tell me look at the configuration

**Comment by HideakiAtsuyo** [comment]
> just you tell me look at the configuration

Because everything is in the default configuration just read correctly i lock the conversation right now.
