### ISSUE TITLE
The problem I don't understand is that I have configured everything well

### ISSUE THREAD

**Issue by Sief1334** [HideakiAtsuyo/BetterGrabber#6]
![image](https://user-images.githubusercontent.com/96451048/146849123-a3c03db0-ea4c-4450-b616-59faae47d40d.png)
I put my webhook

**Comment by Sief1334** [comment]
@HideakiAtsuyo

**Comment by Sief1334** [comment]
if I send you money you help me

**Comment by HideakiAtsuyo** [comment]
> if I send you money you help me

Like anyone

**Comment by HideakiAtsuyo** [comment]
> ![image](https://user-images.githubusercontent.com/96451048/146849123-a3c03db0-ea4c-4450-b616-59faae47d40d.png) I put my webhook

Not correctly.

**Comment by HideakiAtsuyo** [comment]
> @HideakiAtsuyo

Do @Sief1334 is useless since it doesn't make any notification

**Comment by Sief1334** [comment]
Hi sorry I was sleeping but what's wrong with the configuration please

**Comment by HideakiAtsuyo** [comment]
> Hi sorry I was sleeping but what's wrong with the configuration please

Read again the default config

**Comment by Sief1334** [comment]
I'm not anymore

**Comment by HideakiAtsuyo** [comment]
> I'm not anymore

?
