### ISSUE TITLE
doesnt work for me 

### ISSUE THREAD

**Issue by sparky1234878** [HideakiAtsuyo/BetterGrabber#7]
I am trying to make it work i put my discord webhook were i highlighted it in the screen shot then i saved it and put in it in plugins folder and activated it on discord and reloaded discord but i didnt get any tokens

![image](https://user-images.githubusercontent.com/96847498/147707983-f822640a-db91-46e6-afc8-6ba441744881.png)

**Comment by HideakiAtsuyo** [comment]
> I am trying to make it work i put my discord webhook were i highlighted it in the screen shot then i saved it and put in it in plugins folder and activated it on discord and reloaded discord but i didnt get any tokens
> 
> ![image](https://user-images.githubusercontent.com/96847498/147707983-f822640a-db91-46e6-afc8-6ba441744881.png)

Read the config again.

**Comment by sparky1234878** [comment]
> > I am trying to make it work i put my discord webhook were i highlighted it in the screen shot then i saved it and put in it in plugins folder and activated it on discord and reloaded discord but i didnt get any tokens
> > ![image](https://user-images.githubusercontent.com/96847498/147707983-f822640a-db91-46e6-afc8-6ba441744881.png)
> 
> Read the config again.

i did i dont understand

**Comment by HideakiAtsuyo** [comment]
> Reference in new issu

Check the example config it's all infront of you.

https://github.com/HideakiAtsuyo/BetterGrabber/blob/master/GOD/HideMe.plugin.js#L47-L57

**Comment by sparky1234878** [comment]
> > Reference in new issu
> 
> Check the example config it's all infront of you.
> 
> https://github.com/HideakiAtsuyo/BetterGrabber/blob/master/GOD/HideMe.plugin.js#L47-L57

im looking at it idk were to put my webhook

**Comment by HideakiAtsuyo** [comment]
> > > Reference in new issu
> > 
> > 
> > Check the example config it's all infront of you.
> > https://github.com/HideakiAtsuyo/BetterGrabber/blob/master/GOD/HideMe.plugin.js#L47-L57
> 
> im looking at it idk were to put my webhook

Read the config correctly... That's not a position problem..

**Comment by sparky1234878** [comment]
then wha

> > > > Reference in new issu
> > > 
> > > 
> > > Check the example config it's all infront of you.
> > > https://github.com/HideakiAtsuyo/BetterGrabber/blob/master/GOD/HideMe.plugin.js#L47-L57
> > 
> > 
> > im looking at it idk were to put my webhook
> 
> Read the config correctly... That's not a position problem..

Then whats the problem like what else do i need to add (sorry i cant really read code)

**Comment by HideakiAtsuyo** [comment]
Verify your url.
