### ISSUE TITLE
I still dont understand

### ISSUE THREAD

**Issue by sparky1234878** [HideakiAtsuyo/BetterGrabber#8]
![image](https://user-images.githubusercontent.com/96847498/147709325-5ab7b971-890e-41d1-a8b8-8e262f5b643b.png)
can u just please tell me what to put were becuase i tryed everything and it isnt working for me

**Comment by HideakiAtsuyo** [comment]
> ![image](https://user-images.githubusercontent.com/96847498/147709325-5ab7b971-890e-41d1-a8b8-8e262f5b643b.png) can u just please tell me what to put were becuase i tryed everything and it isnt working for me

For the last time, read correctly the config before sending a message.
